import { useEffect, useState } from 'react';
import * as userApi from '../../api/userApi';
import { useAuth } from '../../context/AuthContext';

function Stars({ value }) { return <span className="stars">{'★'.repeat(Math.round(Number(value) || 0))}{'☆'.repeat(5 - Math.round(Number(value) || 0))}</span>; }

export default function StoreListPage() {
  const { user } = useAuth(); const [stores, setStores] = useState([]); const [search, setSearch] = useState({ name: '', address: '' }); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  function loadStores() { const params = {}; if (search.name) params.name = search.name; if (search.address) params.address = search.address; userApi.listStoresForUser(params).then((res) => setStores(res.data.data.stores)).catch((err) => setError(err.response?.data?.message || 'Failed to load stores')); }
  useEffect(() => { loadStores(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  async function handleRate(storeId, rating) { setMessage(''); setError(''); try { await userApi.submitOrUpdateRating({ storeId, rating }); setMessage('Rating saved successfully!'); loadStores(); } catch (err) { setError(err.response?.data?.message || 'Failed to submit rating'); } }
  return <main className="dashboard-page discovery-page"><p className="eyebrow">DISCOVER STORES</p><h2>Welcome, {user?.name?.split(' ')[0] || 'there'} <span>👋</span></h2><p className="page-subtitle">Discover stores and share your experience with the community.</p>{error && <p className="form-alert error-alert">{error}</p>}{message && <p className="form-alert success-alert">{message}</p>}<div className="discovery-search"><input placeholder="⌕  Search stores by name" value={search.name} onChange={(event) => setSearch({ ...search, name: event.target.value })} /><input placeholder="⌖  Filter by address" value={search.address} onChange={(event) => setSearch({ ...search, address: event.target.value })} /><button onClick={loadStores}>Search</button></div><div className="store-grid">{stores.length === 0 ? <div className="empty-state"><span>☆</span><h3>No stores found</h3><p>Try a different search, or come back when new stores are added.</p></div> : stores.map((store) => <article key={store.id} className="store-card"><div className="store-card-art"><span>⌂</span><small>STORERATE VERIFIED</small></div><div className="store-card-body"><h3>{store.name}</h3><p className="store-address">⌖ {store.address || 'Address not available'}</p><div className="overall-rating"><Stars value={store.overallRating} /><strong>{store.overallRating ? Number(store.overallRating).toFixed(1) : 'New'}</strong></div><p className="your-rating">Your rating: {store.userRating ? <Stars value={store.userRating} /> : <em>Not rated yet</em>}</p><div className="interactive-stars" aria-label={`Rate ${store.name}`}>{[1, 2, 3, 4, 5].map((rating) => <button key={rating} onClick={() => handleRate(store.id, rating)} className={Number(store.userRating) >= rating ? 'selected' : ''} aria-label={`${rating} stars`}>★</button>)}</div><small>{store.userRating ? 'Select a star to modify your rating' : 'Select a star to rate this store'}</small></div></article>)}</div></main>;
}
