import { Link } from 'react-router-dom';

export default function HomePage() {
  return <main className="home-page">
    <header className="public-nav"><Link className="logo" to="/"><span>★</span> StoreRate</Link><nav><a href="#how-it-works">How It Works</a></nav><div className="public-nav-actions"><Link className="text-link" to="/login">Login</Link><Link className="button button-primary" to="/signup">Create Account</Link></div></header>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">DISCOVER • RATE • TRUST</p><h1>Discover great stores.<br /><span>Share your experience.</span></h1><p className="hero-description">Find stores, explore customer ratings, and share your experience with a community that values trust.</p><div className="hero-actions"><Link className="button button-primary" to="/signup">Explore Stores →</Link><Link className="button button-secondary" to="/signup">Create Account</Link></div><div className="trust-row"><span className="stars">★★★★★</span><strong>Built for better choices</strong><span>Real reviews. Real confidence.</span></div></div><div className="hero-visual" aria-label="Store rating preview"><div className="hero-orb orb-one" /><div className="hero-orb orb-two" /><div className="store-illustration"><span>⌂</span></div><article className="floating-card main-rating-card"><div className="store-avatar">T</div><div><strong>TechWorld</strong><small>Electronics · Pune</small></div><div className="rating-pill"><span>★</span> 4.8</div></article><article className="floating-card review-card"><span className="review-avatar">A</span><div><strong>Excellent experience!</strong><p><span className="stars">★★★★★</span> Verified review</p></div></article><div className="verified-badge">✓ <span>Verified<br />Reviews</span></div></div></section>
    <section id="how-it-works" className="section how-section"><p className="eyebrow">HOW IT WORKS</p><h2>Better choices, in three simple steps.</h2><div className="steps">{[['01', 'Discover', 'Find stores near you and explore their ratings.'], ['02', 'Rate', 'Share your experience with a simple 1–5 star rating.'], ['03', 'Trust', 'Help other customers make better decisions.']].map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <footer className="public-footer"><div><Link className="logo" to="/"><span>★</span> StoreRate</Link><p>Discover stores.<br />Share experiences.<br />Build trust.</p></div><div><strong>Platform</strong><a href="#how-it-works">How It Works</a></div><div><strong>Account</strong><Link to="/login">Login</Link><Link to="/signup">Create Account</Link></div></footer>
  </main>;
}
