import { useState } from 'react';
import { useNavigate, Link, useLocation } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

const roles = [['user', '◉', 'Normal User'], ['store_owner', '⌂', 'Store Owner'], ['admin', '♜', 'Administrator']];

export default function LoginPage() {
  const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [form, setForm] = useState({ email: '', password: '', selectedRole: 'user' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function handleSubmit(event) { event.preventDefault(); setLoading(true); setError(''); try { const user = await login(form.email, form.password, form.selectedRole); navigate(user.role === 'admin' ? '/admin/dashboard' : user.role === 'store_owner' ? '/owner/dashboard' : '/user/dashboard'); } catch (err) { setError(err.response?.data?.message || 'Login failed'); } finally { setLoading(false); } }
  return <div className="auth-shell"><aside className="auth-aside"><div className="auth-brand">★ StoreRate</div><div><p className="eyebrow">DISCOVER • RATE • TRUST</p><h1>Welcome back to better choices.</h1><p>Continue discovering great stores and sharing your experiences with the community.</p></div><div className="aside-card"><span className="stars">★★★★★</span><strong>Discover with confidence</strong><small>Ratings from people who have been there.</small></div></aside><main className="auth-main"><form className="auth-card" onSubmit={handleSubmit}><Link className="mobile-brand" to="/">★ StoreRate</Link><p className="eyebrow">WELCOME BACK</p><h2>Login to StoreRate</h2><p className="auth-subtitle">Choose your account type to continue securely.</p>{location.state?.message && <p className="form-alert success-alert">{location.state.message}</p>}{error && <p className="form-alert error-alert">{error}</p>}<label>Login As</label><div className="role-picker">{roles.map(([value, icon, label]) => <button type="button" key={value} onClick={() => setForm({ ...form, selectedRole: value })} className={form.selectedRole === value ? 'active' : ''}><span>{icon}</span>{label}</button>)}</div><label>Email<input type="email" placeholder="you@example.com" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /></label><label>Password<input type="password" placeholder="Enter your password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} required /></label><div className="remember-row"><label><input type="checkbox" /> Remember me</label><span>Secure login</span></div><button className="auth-submit" disabled={loading}>{loading ? 'Logging in…' : 'Login →'}</button><p className="auth-switch">New here? <Link to="/signup">Create an account</Link></p></form></main></div>;
}
